# -*- coding: utf-8 -*-
"""SC.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVtg7iBbxID-qEALPlFU6fD780McRXd4
"""

# program hello world


print("Hello, World!")